services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: starburger-backend
    depends_on:
      - frontend
      - db
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: bundles
        target: /app/bundles
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    env_file: .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: starburger-frontend
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"
    volumes:
      - type: volume
        source: bundles
        target: /app/bundles

  db:
    image: postgres:15.3-alpine
    container_name: starburger-db
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data/
    env_file: .env

volumes:
  postgres:
  bundles:
