services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile-backend
    depends_on:
      - frontend
      - db
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"
      ]

    volumes:
      - type: volume
        source: media
        target: /app/media
      - type: bind
        source: .
        target: /app
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
      - target: 5678
        published: 5678
        protocol: tcp
        mode: host

    env_file: .env
    container_name: starburger-backend-dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"
    container_name: starburger-frontend

  db:
    image: postgres:15.3-alpine
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data/
    env_file: .env
    container_name: starburger-db

volumes:
  media:
  postgres:
