#!/usr/bin/bash
set -e
set -o pipefail

frontend_container_name=starburger-frontend
line=-----------------------------------------------------------------------------


echo $line
echo "Stop and remove containers, networks"
docker compose down

echo $line
echo "remote repositories:"
git remote -v

echo $line
echo "pull"
git pull

echo $line
echo "echo "Build images, create and start containers:""
docker compose up -d --build

echo $line
echo "Collect static..."
docker exec -u 0 starburger-backend python manage.py collectstatic --noinput

echo $line
echo migrate...
docker exec -u 0 starburger-backend python manage.py migrate --noinput

echo $line
echo "Stop and remove the $frontend_container_name container (it is useless)"
docker stop $frontend_container_name
docker rm $frontend_container_name

echo $line
echo "Change owner for the media folder"
docker stop $frontend_container_name
docker exec -u 0 starburger-backend chown appuser -R media

echo $line
echo "The deploy completed successfully!"

echo $line


