# Generated by Django 4.1.5 on 2023-01-26 07:31
from typing import List

from django.db import migrations


def fill_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items = OrderItem.objects.prefetch_related('product').all()
    if not order_items.exists():
        return

    items_to_update = []
    for order_item in order_items.iterator(chunk_size=100):
        order_item.price = order_item.product.price
        items_to_update.append(order_item)

    OrderItem.objects.bulk_update(items_to_update, ['price'])


def revert_fill_price(apps, schema_editor):
    apps.get_model('foodcartapp', 'OrderItem').objects.update(
        price=0
    )


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_price_to_orderitem'),
    ]

    operations: List[migrations.RunPython] = [
        migrations.RunPython(fill_price, revert_fill_price)
    ]
