# Generated by Django 4.1.5 on 2023-01-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_fill_price_in_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UP', 'Необработанный'), ('AS', 'Сборка'), ('DE', 'Доставка'), ('CO', 'Выполнен')], db_index=True, default='UP', max_length=2, verbose_name='Статус'),
        ),
    ]
