# Generated by Django 4.1.5 on 2023-01-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_add_order_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CA', 'Наличностью'), ('EL', 'Электронно')], db_index=True, default='CA', max_length=2, verbose_name='Способ оплаты'),
        ),
    ]
