# Generated by Django 4.1.5 on 2023-02-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_related_name_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CA', 'Наличностью'), ('EL', 'Электронно')], db_index=True, max_length=2, null=True, verbose_name='Способ оплаты'),
        ),
    ]
