# Generated by Django 4.1.5 on 2023-02-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_remove_payment_method_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='cooking_restaurant',
        ),
    ]
